fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "admin@inmyfragrance.com"
        sender_name: "no reply"
    
    # use the custom registrationFormType instead the default
    registration:
        form:
            type: App\Form\RegistrationFormType
    # use the custom ChangepasswordFormType instead the default
    change_password:
        form:
            type: App\Form\ChangePasswordFormType
    # use the custom ProfileFormType instead the default
    profile:
        form:
            type: App\Form\ProfileFormType