#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
  path: /
  controller: App\Controller\HomeController::index

ajaxGetBrands:
  path: /get-brands/all/
  controller: App\Controller\HomeController::getBrands