#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
  path: /
  controller: App\Controller\HomeController::index

ajax-brands:
  path: brands/
  controller: App\Controller\HomeController::brands

ajax-products:
  path: /products
  controller: App\Controller\HomeController::products

ajax-search:
  path: /search
  controller: App\Controller\HomeController::search