#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
  path: /
  controller: App\Controller\HomeController::index

ajax-brands:
  path: brands/
  controller: App\Controller\HomeController::brands

ajax-products:
  path: /products
  controller: App\Controller\HomeController::products

ajax-search-by-name:
  path: /searchByName
  controller: App\Controller\HomeController::searchByName

ajax-search-by-family-note:
  path: /searchByFamilyNote
  controller: App\Controller\HomeController::searchByFamilyNote

ajax-search-by-note:
  path: /searchByNote
  controller: App\Controller\HomeController::searchByNote
