#index:
#    path: /
#    controller: App\Controller\DefaultController::index
home:
  path: /
  controller: App\Controller\HomeController::index

api-brands:
  path: brands/
  controller: App\Controller\HomeController::brands

api-products:
  path: /products/{id}/{slug}
  controller: App\Controller\HomeController::products