#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# importation des routes fosuserbundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

home:
  path: /
  controller: App\Controller\HomeController::index

ajax-brands:
  path: brands/
  controller: App\Controller\HomeController::brands

ajax-products:
  path: /products
  controller: App\Controller\HomeController::products

ajax-search-by-name:
  path: /searchByName
  controller: App\Controller\HomeController::searchByName

ajax-search-by-family-note:
  path: /searchByFamilyNote
  controller: App\Controller\HomeController::searchByFamilyNote

ajax-search-by-note:
  path: /searchByNote
  controller: App\Controller\HomeController::searchByNote
